# Generated by Django 4.1.7 on 2023-06-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menci_app', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menci_app.bag'),
        ),
        migrations.DeleteModel(
            name='Validated',
        ),
    ]
